In [15]:
print("Hello")

Hello

In [16]:
import pandas as pd

In [17]:
row_sales = pd.read_csv("raw_sales.csv")
row_sales.head()
row_sales.info()
row_sales.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  5 non-null      int64
 1   customer  5 non-null      str
 2   Product   5 non-null      str
 3   price     5 non-null      int64
 4   quantity  5 non-null      int64
dtypes: int64(3), str(2)
memory usage: 332.0 bytes

       order_id          price  quantity
count  5.000000       5.000000  5.000000
mean   3.000000   30202.400000  3.000000
std    1.581139   44552.147297  2.828427
min    1.000000      12.000000  1.000000
25%    2.000000     500.000000  1.000000
50%    3.000000     500.000000  1.000000
75%    4.000000   50000.000000  5.000000
max    5.000000  100000.000000  7.000000

In [18]:
processed_sales = pd.read_csv("processed_sales.csv")
processed_sales.head()
processed_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     5 non-null      int64
 1   customer     5 non-null      str
 2   Product      5 non-null      str
 3   price        5 non-null      int64
 4   quantity     5 non-null      int64
 5   Total_Price  5 non-null      int64
dtypes: int64(4), str(2)
memory usage: 372.0 bytes

In [19]:
a=b=c=d=30
print(a,b,c,d)
print(a,a,a)
print(b,b)
print(c)

30 30 30 30
30 30 30
30 30
30

In [20]:
a = row_sales.shape
print('ok', a)

b = processed_sales.shape
print('processed', b)

c = row_sales.columns.tolist()
print('ok', c)  

d = processed_sales.columns.to_list()
print('processed', d)

ok (5, 5)
processed (5, 6)
ok ['order_id', 'customer', 'Product', 'price', 'quantity']
processed ['order_id', 'customer', 'Product', 'price', 'quantity', 'Total_Price']

In [21]:
import pandas as pd
df = pd.read_csv(
    "raw_sales.csv",
    header = 0,
    index_col = 0
    )
df.head()

         customer   Product   price  quantity
order_id
1           Rahul    Laptop   50000         5
2            Amit     Mouse     500         1
3           Sneha  Keyboard  100000         7
4            John   Monitor      12         1
5           Priya     Mouse     500         1

In [22]:
l= ["Date",1,2,5,'sai',[7,9,11]]
print(l)
print(l[0])
print(l[-2])
print(l[0:3])

['Date', 1, 2, 5, 'sai', [7, 9, 11]]
Date
sai
['Date', 1, 2]

In [23]:
f = 1
if f%2==0 and f%3==0:
    print("f is divisible by 2 and 3")
elif f%2==0:
    print("f is divisible by 2")
elif f%3==0:
    print("f is divisible by 3")
else:
    print("f is not divisible by 2 and 3")

f is not divisible by 2 and 3

In [24]:
for i in l:
    print(i)

Date
1
2
5
sai
[7, 9, 11]

In [14]:
##Pandas

In [25]:
a = l[1:5]

In [27]:
type(a)

list

In [28]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5])

In [30]:
type(s1)

pandas.Series

In [31]:
d = {'R':[1,2,3,4,5], 'S':[6,7,8,9,10]}

In [33]:
df = pd.DataFrame(d)

In [35]:
type(df)

pandas.DataFrame

In [ ]:
import pandas as pd
df = pd.read_csv('raw_sales.csv')
df.head(1)
df.tail(1)
df.info()
df.columns
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  5 non-null      int64
 1   customer  5 non-null      str
 2   Product   5 non-null      str
 3   price     5 non-null      int64
 4   quantity  5 non-null      int64
dtypes: int64(3), str(2)
memory usage: 332.0 bytes

(5, 5)

In [47]:
df['Product']

0      Laptop
1       Mouse
2    Keyboard
3     Monitor
4       Mouse
Name: Product, dtype: str

In [48]:
type(df['Product'])

pandas.Series

In [52]:
df[['Product','order_id']]

    Product  order_id
0    Laptop         1
1     Mouse         2
2  Keyboard         3
3   Monitor         4
4     Mouse         5

In [53]:
type(df[['Product','order_id']])

pandas.DataFrame

In [ ]:
input("Give me a String: ")

'something'

In [57]:
a = int(input("Enter a number to divide 60-40: "))
part1 = a*60//100
part2 = a*40//100
print("the 60-40 is : ",part1,"-",part2)

the 60-40 is :  600 - 400

In [59]:
a = int(input("Enter a number : "))
if a%2==0:
    print(a, " is even number")
else:
    print(a, "is odd number")

5 is odd number

In [5]:
a = int(input("Enter a number : "))

original = a
reverse = 0

while a>0:
    digit = a % 10 #a = 101, then 101%10=1, then 10%10=0, then 1%10=1
    reverse = reverse * 10 + digit #reverse = 0*10+1=1, then 1*10+0=10, then 10*10+1=101
    a=a//10 #a = 101//10=10, then 10//10=1, then 1//10=0
    
print("Palindrome" if original == reverse else "Not Palindrome")

Palindrome

In [ ]:
m = int(input("Enter a number : "))
original = m
reverse = 0

for i in range(len(str(m))): #len(str(m)) gives the number of digits in m, for example if m=101, then len(str(m))=3, so the loop will run 3 times
    reverse = reverse * 10 + (m%10) #m%10 gives the last digit of m, for example if m=101, then m%10=1, then 10%10=0, then 1%10=1
    m //= 10 #m = m//10 is the same as m = m//10, it gives the number without the last digit, for example if m=101, then m//10=10, then 10//10=1, then 1//10=0
    
print("Palindrome" if original == reverse else "Not Palindrome")

Palindrome

In [ ]:
d = int(input("Enter a number: "))
c = len(str(d))
print(c)

7

In [7]:
#last digit
a = int(input("Enter a number: "))
last_digit = a % 10
print("Last digit:", last_digit)

Last digit: 5

In [ ]:
#middle number
a = int(input("Enter a number: "))  # if a = 123
md = len(str(a))//2 #len(str(a)) gives the number of digits in a, for example if a=123, then len(str(a))=3, so m_d = 3//2 = 1
middle_digit = (a // 10**md) % 10  # a // 10**md gives the number without the last md digits, for example if a=123, then a // 10**1 = 123 // 10 = 12, then 12 % 10 = 2, so the middle digit is 2
print("Middle digit:", middle_digit)

Middle digit: 5

In [17]:
a = list(input("Enter a string: "))
print(a[0])
print(a[-1])

1
9

In [21]:
#sum of digits in a number
a = int(input("Enter: "))
total = 0
for i in str(a):
    total += int(i)
print("Sum of digits:", total)

Sum of digits: 102

In [22]:
#reverse a string or number
a = input("Enter a string or number: ")
print("Reversed:", a[::-1])

Reversed: sa321

In [40]:
import pandas as pd
df = pd.read_csv(r"C:\Users\THS\mst_inv_item_202604011814.csv", encoding='latin-1')
df.head()
df.shape

C:\Users\THS\AppData\Local\Temp\ipykernel_11996\3755600043.py:2: DtypeWarning: Columns (0: item_is_active, 1: item_is_asset, 2: item_is_deleted, 3: item_abc, 4: item_ved) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\THS\mst_inv_item_202604011814.csv", encoding='latin-1')

(23077, 61)

In [ ]:
df.columns["item_id"]
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace(r'[^a-z0-9_]', '', regex=True)
)
print(df.columns)

Index(['item_id', 'created_by', 'created_date', 'item_abbreviation',
       'item_attachment', 'item_code', 'item_is_active', 'item_is_asset',
       'item_is_batch_applicable', 'item_is_deleted', 'item_is_reorder',
       'item_name', 'last_modified_by', 'last_modified_date',
       'item_category_id', 'item_class_id', 'item_department_id', 'item_sc_id',
       'item_scat_id', 'item_section_id', 'item_speciality_id', 'item_ss_id',
       'item_ud_id', 'item_up_id', 'item_cf_conversion', 'abcanalysis',
       'calculatedavgcost', 'isdangerous', 'iseto', 'ishighcostmedicine',
       'ishighriskmedicine', 'islifesavingmedicine', 'isnarcoticdrug',
       'ispsychotropic', 'isscheduleh', 'item_detail_hms_id', 'item_hms_id',
       'item_is_synced_with_hms', 'landedcost', 'purchaserate',
       'purchasetostockingconvfactor', 'remark', 'service_start_date',
       'stockingtosaleconvfactor', 'vedanalysis', 'xyzanalysis',
       'item_depreciation_type_id', 'item_frequency_id', 'item_generic_id',
       'item_manufactured_by_id', 'item_marketing_by_id',
       'item_preganancy_class_id', 'item_route_id', 'item_sub_group_id',
       'item_therauptic_class_id', 'item_org_id', 'is_new_item_code',
       'item_sub_section_id', 'item_abc', 'item_ved', 'item_hsn_code'],
      dtype='str')

In [39]:
a = df['item_id']
print(a.sum())
print(a.mean())
print(a.median())
print(a.max())
print(a.min())
print(a.sum() - a.mean() * len(a))
print(len(a))

266294659
11539.39675867747
11539.0
23079
1
0.0
23077

In [45]:
str1 = input("Enter a string: ")
str2 = input("Enter another string: ") 

compain_str = str1 + str2
print("Combained strig is : ", compain_str)

Combained strig is :  saivishnu

In [63]:
a = int(input("Enter a number: "))
b = int(input("Enter another number: "))
def print_pattern():
    for i in range(b, a - 1, -1):
        print("*" * i)
        
print_pattern()

*****
****
***
**

In [4]:
x = 0
y = 1
while x < 3:
    y *= 2
    x += 1
print(y)

8

In [ ]:
items = [10, 20, 30, 40]
idx = 0
while idx < len(items):
    if items[idx] > 25:
        print("Found!")
    idx += 1

Found!
Found!

In [6]:
n = int(input("Enter a number: "))
sum = 0
i = 1
while i <= n:
    sum += i
    i += 1
print(f"The sum of {n} natural numbers is: {sum}")

The sum of 10 natural numbers is: 55

In [1]:
n = int(input("Enter a number: "))
sum = 0
for i in range(1,n+1):
    sum = sum+i
print(f"The sum of {n} natural numbers is: {sum}")

The sum of 5 natural numbers is: 15

In [15]:
n = int(input("Enter a number: "))
i = 1
while n > 0:
    print('*' * i)
    n -= 1
    i += 1

*
**
***
****
*****

In [9]:
n = int(input("Enter a number: "))
while n > 0:
    print(n*'*')
    n -= 1

*****
****
***
**
*

In [8]:
n = int(input("Enter a number: "))
for j in range(n):
    print('*' * (j + 1))

*
**
***
****
*****

In [7]:
n = int(input("Enter a number: "))
for j in range(n,0,-1):
    print('*' * j)

*****
****
***
**
*

In [22]:
for i in range(20,0,-1):
    if i%2==0:
        print(i)

20
18
16
14
12
10
8
6
4
2

In [29]:
for i in range(20,0,-1):
    if i%2!=0:
        print(i, end=' ')

19 17 15 13 11 9 7 5 3 1

In [38]:
number = int(input("Enter a number: "))
for i in range(1,11):
    print(f"{number} * {i} = {number * i}")

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

In [36]:
number = int(input("Enter a number: "))
i = 1
while i < 10:
    print(f"{number} * {i} = {number * i}")
    i += 1

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27

In [43]:
n=10
sum = 0
i = 1
while i <= n:
    sum += i
    i += 1 
print(sum)

55

In [45]:
sum = 0
for i in range(11):
    sum += i
print(sum)

55

In [49]:
count = 0
str = 'Hello World'
for ch in str:
    if ch == 'o':
        count+=1
print(count)

2

In [50]:
for i in range(4):
    print("****")

****
****
****
****

In [1]:
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50

In [5]:
for i in range(1,11):
    print(i**i)

1
4
27
256
3125
46656
823543
16777216
387420489
10000000000

In [7]:
count = 0
for i in range(1,101,2):
    count+=i
print(count)

2500

In [12]:
str = 'Maruri Sai Vishnu Vardhan Reddy'
count = 0
for ch in str:
    count += 1
print(count)

31

In [20]:
str = 'Srija Pothamshetti'
count = 0
print(str)
for ch in str:
    if ch in 'aeiou':
        count+=1
print(count)

Srija Pothamshetti
6

In [21]:
n = 5
fact = 1

for i in range(1, n + 1):
    fact *= i

print(fact)

120

In [25]:
n = 15
for i in range(1,n+1):
    if n%i==0:
        print(i,"It is a factor")
    else:
        print(i,"not a factor of", n)

1 It is a factor
2 not a factor of 15
3 It is a factor
4 not a factor of 15
5 It is a factor
6 not a factor of 15
7 not a factor of 15
8 not a factor of 15
9 not a factor of 15
10 not a factor of 15
11 not a factor of 15
12 not a factor of 15
13 not a factor of 15
14 not a factor of 15
15 It is a factor

In [ ]:
n = int(input("Enter a number to check prime numner or not : "))
count = 0
for i in range(1,n+1):
    if n%i==0:
        count+=1

if count == 2:
    print(n, "is a prime number")
else:
    print(n, "is not a prime number")

18 is not a prime number